apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: ms-demo
  labels:
    openshift.io/user-monitoring: "true"
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [frontend, emailservice, paymentservice]}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
